---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.9

suites:
  - name: default
    run_list:
      - recipe[test::default]
    attributes:
      common_artifact_repo: <%= ENV['COMMON_ARTIFACT_REPO'] %>
