---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4

suites:
  - name: tuxedo-12-1-1
    run_list:
      - recipe[tuxedo-12-1-1]
    attributes:
      common_artifact_repo: <%= ENV['COMMON_ARTIFACT_REPO'] %>
